package com.example.aetherlauncher.runtime

import android.content.Context
import java.io.File

/** Installs the Phase 4.3 Android LWJGL runtime generated by CI into app-private storage. */
class LwjglRuntimeInstaller(private val context: Context) {
    companion object {
        private const val ASSET_ROOT = "components/lwjgl3"
        private const val INSTALL_DIR = "lwjgl3"
    }

    fun install(): File {
        val target = File(context.filesDir, INSTALL_DIR).apply { mkdirs() }
        val marker = File(target, ".installed")
        if (marker.isFile) return target

        val assetManager = context.assets
        val names = assetManager.list(ASSET_ROOT).orEmpty()
        require(names.isNotEmpty()) {
            "Android LWJGL runtime is missing from the APK. Run the Phase 4.3 GitHub Actions build first."
        }

        copyTree(ASSET_ROOT, target)
        marker.writeText("phase-4.3")
        return target
    }

    private fun copyTree(assetPath: String, target: File) {
        val children = context.assets.list(assetPath).orEmpty()
        if (children.isEmpty()) {
            target.parentFile?.mkdirs()
            context.assets.open(assetPath).use { input ->
                target.outputStream().use { output -> input.copyTo(output) }
            }
            return
        }

        target.mkdirs()
        for (child in children) {
            copyTree("$assetPath/$child", File(target, child))
        }
    }
}
